### ISSUE TITLE
npm published version contains no code

### ISSUE THREAD

**Issue by yyx990803** [thejameskyle/babel-plugin-remove-comments#1]
`lib` was not built :/

**Comment by yyx990803** [comment]
nvm, this doesn't seem to work with Babel 6.

**Comment by thejameskyle** [comment]
Now it does

**Comment by yyx990803** [comment]
Cool! Actually I found out I can just use `comments: false` option for Babel 6, but thanks anyway :)

**Comment by thejameskyle** [comment]
Oh right, I'm an idiot
